### ISSUE TITLE
Relocation related error

### ISSUE THREAD

**Issue by idharmateja** [dharmasam9/moose-core#10]
/usr/bin/ld: hsolve/libhsolve_cuda.a(cuda_compile_generated_AdvanceChannel.cu.o): relocation R_X86_64_32S against `.bss' can not be used when making a shared object; recompile with -fPIC
hsolve/libhsolve_cuda.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: *** [libmoose.so] Error 1
make[1]: *** [CMakeFiles/libmoose.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: hsolve/libhsolve_cuda.a(cuda_compile_generated_AdvanceChannel.cu.o): relocation R_X86_64_32S against`.bss' can not be used when making a shared object; recompile with -fPIC
hsolve/libhsolve_cuda.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: **\* [python/moose/_moose.so] Error 1
make[1]: **\* [CMakeFiles/_moose.dir/all] Error 2
make: **\* [all] Error 2

**Comment by dilawar** [comment]
626d24f should fix this.
